apiVersion: v2
name: pet-battle-api
description: A Helm chart for Kubernetes
type: application
version: 0.0.51
appVersion: pet-battle-api-develop.1
home: https://eformat.github.io/helm-charts
maintainers:
- name: eformat
